### ISSUE TITLE
OSH Park Unsupported Drilled Slots

### ISSUE THREAD

**Issue by sparksterz** [AidanHockey5/STM32_VGM_Player_YM2612_SN76489#1]
Hey, I was looking to build one of these, but having no knowledge of PCB layout and tools to generate them with I'm wondering if this is something to be concerned about.

Unfortunately they don't really give much info on which slots...and it's flagged as just a warning. I'm able to generate this by uploading the zipped gerber files. using the kicad_pcb file directly doesn't seem compatible. I assume due to the version of kicad being newer? Not sure.

Here is the information they give me from the zipped gerber files:

Processing information
* Processing Megablaster_Gerber.zip as KiCad ZIP file. 
* 2 layer board of 5.46x3.61 inches. 
* Your project contains 2 drill files, we've merged them. ["STM32_MegaBlaster-NPTH.drl", "STM32_MegaBlaster-PTH.drl"] 

Warning (non-critical)
* Detected unsupported drilled slots.

As far as I can tell by their thumbnail board renders this might be the slots near the DC power jack and/or maybe the audio jack? They seem to look a bit strange on their generated image. Here's the [link to the image that was generated](https://644db4de3505c40a0444-327723bce298e3ff5813fb42baeefbaa.ssl.cf1.rackcdn.com/67f2c8f53406d2f81542bcc66bbe4da2.png)

Is there another preferred vendor to use? I know a minor amount about electronics from bread board type work, but nothing about prefabricated PCBs.

**Comment by AidanHockey5** [comment]
Hello Brian!

Yep! It's a good thing you caught that because your DC jack wouldn't fit
with holes like that!

I recommend using JLCPCB - it's who I went with for this project. They'll
give your more boards for less money to boot. The zipped Gerber files I
created are to their specifications, so they should work without a hitch.

Let me know if you have any more questions!

-Aidan
