### ISSUE TITLE
Some VGMs are freezing.

### ISSUE THREAD

**Issue by MakerLab-Vector** [AidanHockey5/STM32_VGM_Player_YM2612_SN76489#10]
Everything works from VGMRips except some Contra tracks. But every track from DefleMask doesn't work at all. Even if it doesn't contain any samples and file sizes are small. Player just freezes. Previously i made ym2151 player(not your player, by Hiromasa Tanaka) and it works with all VGMs perfect. Why is it happening? There is so much fan made tracks and covers that just better than originals. Thank you for support. 😃

**Comment by AidanHockey5** [comment]
Hello,

So, YM2151 tracks are very simple to play as they’re generally FM-only. PCM
samples are delegated to other chips. YM2612s feature on-board DACs, so the
PCM samples are expected in almost all soundtracks, thus quite an excessive
amount of RAM is required to handle all that extra sample data.

This player was an earlier version of my Mega Blaster design that featured
an STM32 microcontroller that didn’t have very much RAM, so PCM sample size
was limited. Furthermore, advanced functions like DAC Streams were never
implemented due to the limitations of the platform.

Therefore, VGM tracks that have very large PCM sample storage requirements
are skipped automatically by the player and any tracks that utilize DAC
streams (often utilized by home brew composers), will cause the player to
error out.

All of these issues have been fixed in my latest revision of the Mega
Blaster project found here:
https://github.com/AidanHockey5/MegaBlaster2

This upgraded version of the project has a far more capable
microcontroller, lots more internal RAM, and even more external RAM. It’s
better in just about every way and supports DAC streams and tracks with
demanding PCM requirements.

The original Mega Blaster project (this repository), is no longer updated
as it has been superseded by its successor. I apologize for any
inconvenience, but the advanced features of the VGM specification really
did require much more capable hardware, so a board revision was necessary.

**Comment by MakerLab-Vector** [comment]
I mean... It can easily play Streets of Rage 2 intro that is 1705kb(or something around it). But can't play 2kb test that i made in DefleMask which contains only four notes and no samples at all. Just freezes and it's all.

**Comment by MakerLab-Vector** [comment]
I think I know what to do. I can run vgm player in sega emulator and then rip off vgm from emulator while it's playing. I tested this player before with emulator and on real mega drive 2 with flash cart.

**Comment by MakerLab-Vector** [comment]
Maybe DefleMask codes tracks in VGM different way. Like VGM versions and etc.

**Comment by AidanHockey5** [comment]
If there are no samples, then deflemask may be exporting compressed “VGZ”
files, which are definitely not supported on the old Mega Blaster.
You may be able to use 7zip to extract the standard VGM file from the VGZ
file if it is indeed compressed.

**Comment by MakerLab-Vector** [comment]
No. It's VGM. There is nothing to unzip. And ym2151 player i made can play only vgm too. But i just export vgm,drop on sd and it's working. idk what happening 🤨

**Comment by MakerLab-Vector** [comment]
Jesus... It worked! Even if file size is 9mb
